47 게시글 등록 기능을 구현한다
WithPeace/with-peace-android pull request #51
Opened 2024-03-12 07:14 UTC by chws0508

## 관련 이슈번호

<br/> close #47

## 작업 사항
- 게시글 등록 모듈 구현
- 이미지 권한 모듈 구현
- 갤러리 모듈 구현
<br/>

## 기타 사항

<br/>

2024-03-12 10:58 UTC, rhkrwngud445 requested changes
상당히 Speedy하고 직관적인 코드입니다! 리뷰 확인 부탁드립니다!

2024-03-12 10:58 UTC, rhkrwngud445 commented on app/src/main/AndroidManifest.xml
> +
사용하지 않는 권한은 플레이스토어 리젝 사유가 되는 것으로 알고있습니다 커스텀 갤러리에서 비디오와 오디오 권한이 꼭 필요한가요?!

2024-03-12 10:58 UTC, rhkrwngud445 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetLocalImagesUseCase.kt
> +class GetLocalImagesUseCase @Inject constructor(
GetImagesUseCase는 어떤가요?!

2024-03-12 10:58 UTC, rhkrwngud445 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetLocalImagesUseCase.kt
> +                pageSize = 9841,
어떤의미의 숫자인가요?

2024-03-12 10:58 UTC, rhkrwngud445 commented on core/imagestorage/src/main/java/com/withpeace/withpeace/core/imagestorage/DefaultImageDataSource.kt
> +        val imageCursor = context.getImageCursor((page - 1) * loadSize, loadSize, folder)
-1의 의미는 무엇일까요?! 상수로 대치 가능할까요?!

2024-03-12 10:58 UTC, rhkrwngud445 commented on gradle/libs.versions.toml
> +
페이징을 사용하면 어떤 이점이 있나요?!
메모리내 자동 캐싱이 된다고 하는데, 이미지 로딩 라이브러리와 중복 캐싱 문제는 없나요?!

2024-03-12 10:58 UTC, rhkrwngud445 commented on feature/gallery/src/main/java/com/withpeace/withpeace/feature/gallery/GalleryViewModel.kt
> +    private val getLocalImagesUseCase: GetLocalImagesUseCase,
위 커멘트처럼 Naming getImageUseCase 어떠신가요?!

2024-03-12 10:58 UTC, rhkrwngud445 commented on feature/gallery/build.gradle.kts
> +    implementation(libs.skydoves.landscapist.glide)
해당 라이브러리는 기존 이미지 라이브러리에 비해 어떤 이점이 있나요
?!

2024-03-12 11:09 UTC, rhkrwngud445 commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize|screenLayout"
어떤 목적으로 추가되었을까요?!

2024-03-12 11:09 UTC, rhkrwngud445 commented on app/build.gradle.kts
> +    }
요 친구는 어떤 친구인가요?!

2024-03-12 11:09 UTC, rhkrwngud445 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/util/image.kt
> +private const val HIGHEST_COMPRESS_QUALITY = 100
깔끔~👍😀

2024-03-12 13:28 UTC, chws0508 commented on gradle/libs.versions.toml
> +
이미지 로딩 라이브러리는 BitMap을 캐싱하는 거고, 페이징은 페이징 데이터를 캐싱하는 것이라서, 중복 캐싱은 괜찮을 것 같아요.

2024-03-12 13:32 UTC, chws0508 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetLocalImagesUseCase.kt
> +                pageSize = 9841,
이전 커밋의 있는 기능으로, 이 기능은 삭제되었어요!

2024-03-12 13:34 UTC, chws0508 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetLocalImagesUseCase.kt
> +class GetLocalImagesUseCase @Inject constructor(
이 UseCase가 직접적으로 내부 이미지들을 가져오는 기능이라, Local이 들어가는게 직관적이라고 생각되는데 어떻게생각하시나요?

2024-03-12 13:35 UTC, chws0508 commented on app/src/main/AndroidManifest.xml
> +
이전 커밋이라 남아있는것 같네요! 추후 커밋에서 삭제하였습니다!

2024-03-12 13:36 UTC, chws0508 commented on feature/gallery/build.gradle.kts
> +    implementation(libs.skydoves.landscapist.glide)
기존 Coil이나 Glide는 Preview기능을 제공하지 않는데에 비해, 이 라이브러리르 사용하면 Preview 기능을 제공하고, 로딩 기능(placeHolder) 기능도 제공해서 많은 메리트가 있다고 생각합니다! 거의 대중적으로 사용되고 있어요!

2024-03-12 13:37 UTC, chws0508 commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize|screenLayout"
https://www.notion.so/TextField-1ea9e65e3cfb4b1298bbe1741a26e614?pvs=4

configurationChanges 는 화면회전하니까 터져서 그것 방지하기위해 추가했습니다

2024-03-12 13:38 UTC, chws0508 commented on app/build.gradle.kts
> +    }
이전 프로젝트를 진행할 때, 저렇게 안해주면 라이브러리끼리 패키지 충돌이 나더라구요... 그것을 방지하기 위해 추가해주었습니다

2024-03-12 13:48 UTC, rhkrwngud445 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetLocalImagesUseCase.kt
> +class GetLocalImagesUseCase @Inject constructor(
Data Layer에서 이미지를 가져오므로 usecase는 어디서 이미지를 가져오는지는 몰라도 될 것 같아요!

2024-03-12 13:49 UTC, rhkrwngud445 commented on core/imagestorage/src/main/java/com/withpeace/withpeace/core/imagestorage/DefaultImageDataSource.kt
> +        val imageCursor = context.getImageCursor((page - 1) * loadSize, loadSize, folder)
imageCursor 변수명에도 알기 힘들어서, 지금도 page-1이 어떤 의미인지 안 와닿는 것 같습니다🧐 왜 -1을 하는 것일까요?!

2024-03-12 14:29 UTC, rhkrwngud445 commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize|screenLayout"
configurationChanges를 적용하면, 구성변경시 일어나는 리소스 최적화를 직접 수행해야하는 것으로 알고있습니다.
https://developer.android.com/guide/topics/manifest/activity-element.html?hl=ko#config
다른 해결 방법은 없을까요?!

2024-03-12 17:56 UTC, rhkrwngud445 commented on app/src/main/java/com/withpeace/withpeace/MainActivity.kt
> +                        composeStart(REGISTER_POST_ROUTE)
롤백 부탁드립니다 나도 하고 있는 중ㅋㅋ

2024-03-12 19:09 UTC, chws0508 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetLocalImagesUseCase.kt
> +class GetLocalImagesUseCase @Inject constructor(
이 경우에는 정확히 앨범에서 이미지를 가져오는 기능이기 때문에, getImagesUsecase 는 조금 추상적인것 같아요. 나중에 이미지를 가져오는 다른 기능이 생겼을 때 구분이 가능할까요? 그리고 시간이 지나서 봤을 때 getImagesUsecase만 보고 이 기능이 어떤 기능인지 알 수 있을까요? Local이 맘에안든다면 getGalleryImagesUsecase 또는 getAlbumImagesUseCase이미지는 어떤가요?

2024-03-13 04:00 UTC, rhkrwngud445 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetLocalImagesUseCase.kt
> +class GetLocalImagesUseCase @Inject constructor(
맞습니다 구체적일 필요가 있군요! 이미지는 내부에서 가져오는 것보다 갤러리로 부터 가져온다가 명확한 의미를 가질 것 같습니다!

2024-03-14 09:26 UTC, rhkrwngud445 approved these changes
따봉 27개정도 드립니다 👍X27

2024-03-18 06:47 UTC, merged