Feat/#43 프로필 기능을 개발한다
WithPeace/with-peace-android pull request #63
Opened 2024-03-20 14:21 UTC by rhkrwngud445

## 관련 이슈번호

<br/> close #43 

## 작업 사항

<br/>
- 프로필 화면
- 프로필 편집

## 기타 사항

<br/>

2024-03-20 15:23 UTC, rhkrwngud445 commented
WindowCompat.setDecorFitsSystemWindows(window, false)
이 코드를 쓰니,
WithpeaceBackButtonTopAppbar 위치가 상이해서 현재 주석처리 했습니다 
`kotlin
WindowCompat.setDecorFitsSystemWindows(window, false)
` 요 친구의 히스토리를 알 수 있을까요?!
<img width="289" alt="스크린샷 2024-03-21 오전 12 00 33" src="https://github.com/WithPeace/with-peace-android/assets/33768873/a1171d8e-e669-495f-8996-68bd5b1b6f2d">

2024-03-21 11:50 UTC, chws0508 commented
https://jaeryo2357.tistory.com/92
저 코드의 역할은 SystemBar(안드로이드 시계,배터리정보 등등)까지 content 영역을 확장시킬수 있게 하는 함수입니다. false로 하게되면 그 영역까지 확장이 가능하게 하는겁니다. 
 enableEdgeToEdge() 이걸로 대체가 가능하구요.
 왜 저걸 사용했냐면, 키보드가 올라올 때 컨텐츠도 같이 올라가게 하려면 SystemBar 영역까지 content가 확장이 가능하게 하기 위함입니다.
 WithpeaceBackButtonTopAppbar 위치가 상이한 이유가 저 이유인지는 잘 모르겠네요

2024-03-30 06:36 UTC, chws0508 requested changes
고생 많으셨습니다...
코멘트 남겼으니 확인 부탁드립니다!

2024-03-30 06:36 UTC, chws0508 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/UpdateProfileUseCase.kt
> +    }
또한 이건 제 개인적인 스타일로는, 닉네임만 변경되었는지, profile만 변경되었는지에 대한 함수를 ChangingProfileInfo로 전가할 것 같아요. Usecase에서는 그 함수를 이용하고요.

2024-03-30 12:32 UTC, rhkrwngud445 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
> +            }
resposne가 string 타입인줄 알았네요🥲
또한 return에 대해서, flow가 emit을 안하면 메모리 누수가 발생하는 줄 알았는데, 아니었군요..
`return emit(Unit)` 으로 바꾸었습니다.

`onError(WithPeaceError.GeneralError(code = 2))`
해당 코드는 "닉네임이 중복이다"는 오류를 도메인 오류로 핸들링 하기 위한 코드입니다.

숫자에 대해서는 임의로 정한 것인데 이는 논의가 더 필요해 보입니다.
개인적으로 WithPeaceErrorCode를 만들어 서버, 클라이언트단 에러 코드를 같이 관리하면 좋겠다고 생각하고 있습니다.

2024-03-30 12:56 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
> +                },
> 1,2 는 임의로 하신걸까요?
맞습니다.
https://github.com/WithPeace/with-peace-android/pull/63#discussion_r1545332325
해당 코멘트랑 같이 의견 나누어보면 좋을 것 같아요!

> 이벤트를 날리는 것이 아니라, 직접 상태를 바꾸면 될 것 같아요
Duplicated InvalidedFormat 경우에 Nickname 변경을 하면 하단 빨간 문구가 보여지고 하단 버튼을 클릭하면 스낵바가 출력됩니다.
후자인 스낵바 상태를 나타내기 위해 Event 발생이 필요했어요!




> ```kotlin
>  fun verifyNickname() {
>         viewModelScope.launch {
>             profileEditUiState.collectLatest {
>                 if(it is ProfileEditUiState.Editing){
>                     delay(500L)
>                     verifyNicknameUseCase(...)
>                 }
>             }
>         }
> ```
> 
> view에서 함수를 호출하는 것이 아닌, 이런식으로도 가능할 것 같습니다.

해당방식도 좋아보입니다! 코드가 더 깔끔해지는 것 같아요! 저는 View 회원가입에서도 쓰이기 때문에, Screen을 통해서 구현하면 재활용성이 좋아 보였습니다.

2024-03-30 12:59 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/navigation/ProfileEditorNavigation.kt
> +    val encodedUrl = URLEncoder.encode(profileImageUrl, StandardCharsets.UTF_8.toString())
url을 넘기는 경우에 이를 네비게이션이 deeplink로 인식하여 오류가 발생했습니다.
이를 해결하기 위해 인코딩을 하여 넘겨주었어요!

2024-03-30 15:15 UTC, rhkrwngud445 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/UpdateProfileUseCase.kt
> +    }
```
sealed interface ProfileChangingStatus {
    data object OnlyNicknameChanging : ProfileChangingStatus
    data object OnlyImageChanging : ProfileChangingStatus
    data object AllChanging : ProfileChangingStatus

    companion object {
        fun getStatus(
            beforeProfile: ChangingProfileInfo,
            afterProfile: ChangingProfileInfo,
        ): ProfileChangingStatus {
            return if (beforeProfile.profileImage != afterProfile.profileImage
                && afterProfile.nickname != beforeProfile.nickname && afterProfile.profileImage != null
            ) {
                AllChanging
            } else if (afterProfile.profileImage != null && beforeProfile.profileImage != afterProfile.profileImage
            ) {
                OnlyImageChanging
            } else {
                OnlyNicknameChanging
            }
        }
    }
}
```

해당 코드를 추가하여 when문을 없애고 수정하였습니다! ChangingProfileInfo는 편집시에만 필요한 회원정보를 의미하며, ProfileChangingStatus가 객관적인 상태 분류에 적합할 것이라고 생각했습니다!

2024-03-30 15:35 UTC, chws0508 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/UpdateProfileUseCase.kt
> +    }
when문을 안쓰시는 이유가 있을까요...?

2024-03-30 15:37 UTC, chws0508 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
> +            }
닉네임 중복에서 true면 onError를 발생시키는 것이 좀 어색해보입니다. 그냥 emit(false)를 보내고 usecase나 viewmodel단에서 처리해야 할 것 같아요

2024-03-30 15:40 UTC, chws0508 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
> +                },
빨간 문구가 보여지는것은 상태이고, 스낵바가 호출되는 것은 부수효과라고 생각됩니다. 따라서 두개를 구분해서 상태와 이벤트로 관리해야 한다고 생각해요.

2024-03-30 16:01 UTC, rhkrwngud445 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/UpdateProfileUseCase.kt
> +    }
저는 when의 파라미터를 잘 활용할 수 있는 경우나 else를 안쓸 수 있는 경우에 when을 선호하고 있었습니다. 

```
sealed interface ProfileChangingStatus {
    data object OnlyNicknameChanging : ProfileChangingStatus
    data object OnlyImageChanging : ProfileChangingStatus
    data object AllChanging : ProfileChangingStatus

    companion object {
        fun getStatus(
            beforeProfile: ChangingProfileInfo,
            afterProfile: ChangingProfileInfo,
        ): ProfileChangingStatus {
            return when {
                beforeProfile.profileImage != afterProfile.profileImage &&
                    afterProfile.nickname != beforeProfile.nickname &&
                    afterProfile.profileImage != null -> AllChanging
                afterProfile.profileImage != null &&
                    beforeProfile.profileImage != afterProfile.profileImage -> OnlyImageChanging
                else -> OnlyNicknameChanging
            }
        }
    }
}
```

if문 가독성이 조금 더 나아보이는 것도 있네요! 다른 좋은 표현 방법이 있을까요?!

2024-03-30 16:20 UTC, rhkrwngud445 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
> +            }
닉네임 중복을 비즈니스 오류로 판단하였습니다! 그래서 WithPeaceError와 함께 쓰이면 좋지 않을까라는 생각에서 코드를 짜보았는데요!

해당 방법을 채택한 생각의 흐름은 아래와 같습니다.
- viewModel까지 boolean 전파시키는 것은 verifyNicknameUseCase에서 어색할 것 같았습니다. (format에러인지, duplicate인지 알기 어려운 문제가 있었습니다.)
- 이를 구분하기 위해 따로 onError() 또는 usecase flow response를 통해 구분해야 했습니다.
- 해당 방법 모두 domain을 만들어서 구분이 필요했는데, 에러라는 도메인이라고 생각되었습니다. 
- 그래서 WithPeaceError에서 같이 핸들링 처리를 고려했습니다.

2024-03-30 17:02 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
> +                },
깨달음을 얻었습니다

2024-03-30 17:05 UTC, rhkrwngud445 commented on feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/MyPageScreen.kt
> +    }
Channel을 이용하는 이유가 sharedFlow와 다르게, 에러 값이 캐싱되었다가 방출한다는 점이 맞을까요?!

2024-03-30 17:40 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
> +        }
1. onError를 suspend로 감싸서 viewModelScope.launch가 한 번만 사용되도록 했습니다!
2. 맞습니다! 기획상으로 해당 로직이 수행됩니다

2024-03-31 05:40 UTC, chws0508 commented on feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/MyPageScreen.kt
> +    }
네 맞습니다. Channel은 기본값으로 버퍼에다가 값을 저장해놓습니다. (Default가 64개 원소를 저장하는 것으로 알고있음) 
그러나 Channel 은 한 소비자당 하나의 원소를 가질 수 있다는 점이 단점이고, SharedFlows는 여러 소비자가 같은 값을 공유해서 받을 수 있다는 장점이 있습니다. 
따라서, 여러 소비자가 같은 같은 값을 관찰해야 한다면, SharedFlow를 쓰고, 아니라면 Channel을 쓰는것이 좋습니다.

2024-03-31 05:44 UTC, chws0508 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/UpdateProfileUseCase.kt
> +    }
if문이 3개가 넘어가면 when문을 쓰는 것이 저는 가독성이 좋아보입니다.

2024-03-31 06:00 UTC, chws0508 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
> +            }
저는 verifyDuplicated 함수인데, true를 뱉는것이 OnError라고 판단되는 것이 저는 더 어색해보였습니다. verfiyDuplicated는  WithpeaceError는 저희가 의도하지 않은 에러에 대해서 처리하는 것이 좋지 않을까 하는 생각입니다. Usecase에서 Boolean 상태값을 뱉는 것이 아니라, 닉네임 상태를 구분하는 Sealed Class를 만드는 것은 어떨까요?

```kotlin
sealed interface NicknameValidation {
    data object DuplicationError:NicknameValidation
    data object FormatError:NicknameValidation
    data object Success:NicknameValidation
}
```

2024-03-31 06:30 UTC, rhkrwngud445 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/UpdateProfileUseCase.kt
> +    }
좋습니다 3개의 분기가 넘어가면 when을 쓰는 것으로 하겠습니다! 이 또한 컨벤션이 되겠네요!

2024-03-31 07:13 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileModelMapper.kt
> +}
nickname 대한 require exception이 발생했습니다. 
잘못된 닉네임이라도 Update API 요청을 할 수 있기 때문에 현재 해당 require을 제거하였습니다.
고민이 되는 부분이 nickname에 대한 중복 검사 API는 있지만, format validate API는 없습니다. 이에 nickname 역할이 모호해지네요

2024-03-31 07:55 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
> +            updateData
같은 값인지에 대한 비교는 viewModel에서 해도 괜찮을 것 같아요! UI 상태가 이전과 같은 비교하는 것은 viewModel이 할 수 있다고 생각합니다! 스캇 제안 방식이 아래 방식이 맞을까요?!

``` 
val changingUiState = _profileEditUiState.value.currentProfileInfo.copy(
            nickname = _profileEditUiState.value.currentProfileInfo.nickname,
            profileImage = imageUri,
        )
        _profileEditUiState.update {
            return@update if (baseProfileInfo.toDomain().equals(changingUiState)
            ) {
                _profileEditUiState.value.copy(
                    currentProfileInfo = changingUiState,
                    isChanged = false,
                )
            } else {
                _profileEditUiState.value.copy(
                    currentProfileInfo = changingUiState,
                    isChanged = true,
                )
            }
        }
```

2024-03-31 07:56 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
> +            updateData
그 외에 프로필이 isChanged를 가지고 있는 것은 확실히 좋은 것 같아 수정하였습니다!

2024-03-31 08:45 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
> +                },
수정했습니다

2024-03-31 08:48 UTC, rhkrwngud445 commented
@chws0508 
viewModel.getProfile(), ChangedProfile 리뷰 경우에 바뀐 프로필에 대한 정보를 Response를 통해 가져오는 것으로 고려하고 있는데요!
API에서 profile 전체 변경 후 imageUrl만 내려주고 있어, 변경 요청 드린 상태입니다.
현재 이 부분이 크리티컬하지 않아 따로 이슈파서 진행토록 하겠습니다!

2024-03-31 19:21 UTC, chws0508 requested changes

2024-03-31 22:49 UTC, rhkrwngud445 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
> +            }
스캇의 의도대로라면 usecase의 onError() 함수 파라미터 정의는 어떻게 될까요?!

2024-03-31 23:02 UTC, rhkrwngud445 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
> +            }
서버에서 해당 validation을 검증해주는 경우 또한 의도치 않은 에러에 해당될까요?

updateProfile API에서는 nickname에 대한 validate를 400번대 response code로 받아 WithPeaceError로 처리하고 있습니다

서버에서 하는 validate 우리 도메인에서 하는 validate는 같은 성격을 띄고 있다고 생각하고 있습니다.

2024-04-01 05:29 UTC, rhkrwngud445 commented on core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/profile/Nickname.kt
> +        fun create(value: String): Nickname = Nickname(value)
해당 메소드를 통해 자연어처럼 읽히길 원했습니다! Nickname(nickname) Nickname.create(nickname)

2024-04-01 05:32 UTC, rhkrwngud445 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileModelMapper.kt
> +}
저도 require 두는 것은 좋은 것 같은데요! ValidNickname, Nickname으로 구분을 해볼까요?! string과 Nickname은 역할 구분이 어려워 보입니다!

2024-04-01 11:44 UTC, chws0508 requested changes

2024-04-01 11:44 UTC, chws0508 commented on feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
> +    }
이건 함수로 안해도 될 것 같아요

2024-04-01 11:44 UTC, chws0508 commented on feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/MyPageScreen.kt
> +    }
코드 바꿔주세용

2024-04-01 11:44 UTC, chws0508 commented on feature/profileeditor/src/main/java/com/app/profileeditor/uistate/ProfileEditUiEvent.kt
> +    data object UnAuthorized : ProfileEditUiEvent
네이밍 바꿔 주세용

2024-04-01 15:08 UTC, merged