Feat/#67 게시글 목록 기능 구현
WithPeace/with-peace-android pull request #79
Opened 2024-04-04 13:21 UTC by chws0508

## 관련 이슈번호

<br/> close #67

## 작업 사항

<br/>

## 기타 사항

<br/> PostTopicUiState가 Domain을 가지고 있는 것은 나중에 한번에 바꾸겠습니다. 등록기능도 다 바꿔야해서,
그리고 DateLogic에 현재 오류가 있는데 곧 수정하겠습니다

2024-04-04 17:12 UTC, rhkrwngud445 commented
고생하셨습니다!
코드 리뷰에 앞서 QA 진행 중입니다.
<img width="286" alt="스크린샷 2024-04-05 오전 2 02 37" src="https://github.com/WithPeace/with-peace-android/assets/33768873/acaf1c00-5e44-4331-a277-7c1e3837b1a4">
이미지 라운드 처리 부탁드립니다!

또한 현재 새로고침에 대한 기능이 없는 것으로 보이는데, 아직 논의되지 않은 것일까요?!

2024-04-04 17:39 UTC, rhkrwngud445 requested changes
고생하셨습니다! 궁금한 점 위주로 남겼는데, 확인 부탁드립니다!

2024-04-04 17:39 UTC, rhkrwngud445 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultPostRepository.kt
> +                    onError(GeneralError(statusCode.code, messageOrNull))
해당 API도 401에 대한 처리가 필요해 보입니다

2024-04-04 17:39 UTC, rhkrwngud445 commented on core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/post/PostTopicResponse.kt
> +}
Serialziable로 직렬화 가능한데 SerialName으로 선언하신 이유가 있을까요?!

2024-04-04 17:39 UTC, rhkrwngud445 commented on core/ui/src/main/java/com/withpeace/withpeace/core/ui/PostTopicUiState.kt
> +    val index: Int,
tabIndex로 보이는데 맞을까요?!

2024-04-04 17:39 UTC, rhkrwngud445 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +    LaunchedEffect(null) {
uiEvent를 인자로 넣었었는데, null로 해도 동작이 동일한가요?!

2024-04-04 17:39 UTC, rhkrwngud445 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +                    )
혹시 오피셜 로직인가요? 임시로 넣어두신 걸까요?!

2024-04-04 17:39 UTC, rhkrwngud445 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +                }
이 부분도 임시로직인가요?

2024-04-04 17:39 UTC, rhkrwngud445 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +            is LoadState.NotLoading -> {
성공 대신에 NotLoading 네이밍을 채택하신 이유가 무엇일까요?!

2024-04-04 17:39 UTC, rhkrwngud445 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +            val post = postListPagingData[it] ?: throw IllegalStateException()
어떤 경우에 null일까요?! 빈 데이터 대신에 throw를 하시는 이유가 있을까요?!

2024-04-05 04:27 UTC, chws0508 commented on core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/post/PostTopicResponse.kt
> +}
Enum 클래스는 Serializable을 선언할 필요가 없습니다! SerialName은 필수라고 생각했는데, 아니여서 제거하였습니다.

2024-04-05 04:28 UTC, chws0508 commented on core/ui/src/main/java/com/withpeace/withpeace/core/ui/PostTopicUiState.kt
> +    val index: Int,
tab 말고도 자신의 위치를 알아야 하는 UI 가 있다고 판단해서 index로 지었습니다

2024-04-05 07:15 UTC, chws0508 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +    LaunchedEffect(null) {
LaunchedEffect의 키가 달라지면, 내부 문을 취소하고 다시 실행시키는 것인데, collect를 취소할 필요가 없으므로 null로 하는 것이 적당하다고 생각해요

2024-04-05 07:17 UTC, chws0508 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +                    )
임시 로직입니다. 추후 스켈레톤을 쓰는 것이 어떨지 합니다.

2024-04-05 07:17 UTC, chws0508 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +                }
네 이부분도 네트워크가 끊겼을 때 보여주는 화면을 디자이너님에게 요청하여 공통으로 적용해야 할 것 같습니다.

2024-04-05 07:18 UTC, chws0508 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +            is LoadState.NotLoading -> {
Paging LoadState에는 성공 상태가 따로 없습니다. Loading,Error,NotLoading이 있는데 NotLoading이 성공 상태라고 봐도 무방합니다.

2024-04-05 07:19 UTC, chws0508 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +            val post = postListPagingData[it] ?: throw IllegalStateException()
제가 생각하기에는 Null일 경우가 있을 수가 없다고 생각하여서 에러를 발생시키도록 하였습니다.

2024-04-05 07:21 UTC, chws0508 commented
리뷰 반영 완료하였고, 화면 회전할때마다 Collect를 새로하여 flatMap로직이 실행되어서, 그냥 pagingData를 MutableStateFlow로 두고 onTopicChanged 함수가 불릴때마다 업데이트 하도록 수정하였습니다.

2024-04-05 07:52 UTC, rhkrwngud445 commented on feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
> +            val post = postListPagingData[it] ?: throw IllegalStateException()
postListPagingData.get() 메소드는 왜 nullable 한 값을 리턴할까요?!

2024-04-05 08:10 UTC, rhkrwngud445 commented
https://github.com/WithPeace/with-peace-android/pull/79#issuecomment-2037755729
답변 확인했습니다! 해당 코멘트만 확인 부탁드립니다

2024-04-05 08:12 UTC, chws0508 commented
기획 요구사항에는 없었는데, 지훈님께 기회되면 물어보겠습니다

2024-04-05 09:35 UTC, merged