Paging 성능 개선 및 테스트 작성
WithPeace/with-peace-android pull request #89
Opened 2024-04-16 17:09 UTC by chws0508

## 관련 이슈번호

<br/> close #83 
close #71

## 작업 사항
- LazyColumn ket 추가
- Data영역으로 PagingSource 파일 이동
- PagingSource 테스트 작성
- ViewModel 테스트 작성
<br/>

## 기타 사항

<br/>

2024-04-17 07:16 UTC, chws0508 commented
> 리뷰에 앞서 Paging 성능 개선은 어떻게, 어떤 부분에서 진행하였는지 알 수 있을까요?!

성능 개선이라는 표현을 제가 잘못 선택한 것 같습니다. 주 작업은 성능 개선이라기 보다는, Domain에 Paging 라이브러리가 있다보니, 테스트가 불가능한 문제가 생겨서, Paging 부분을 안드로이드 의존성이 있는 Data 영역으로 옮기는 작업이 주라고 보면 될 것 같습니다. 
LazyColumn에 Key를 추가한것이 어떻게 보면 성능을 개선한 것이라고 보면 될 것 같습니다.

2024-04-17 11:17 UTC, rhkrwngud445 requested changes
고생하셨습니다! 레이어가 좀 더 추상화 되었고, 꼼꼼한 테스트 해주셨네요👍
궁금한 것과 지금 PR과 관계 없지만 작은 QA 남겼습니다 확인 부탁드립니다!

2024-04-17 11:17 UTC, rhkrwngud445 commented on core/ui/src/main/java/com/withpeace/withpeace/core/ui/DateUiModel.kt
> +    val duration: Duration
서버 이슈 같긴한데 글을 올렸을 때 -3초 전이라고 뜨네요! 확인 부탁드립니다!
> 2024-04-17 20:00:48.882 18571-23927 okhttp.OkHttpClient     com.withpeace.withpeace              I  {"data":{"postId":304,"userId":5,"nickname":"nickna","profileImageUrl":"http://withpeace.s3-website.kr.object.ncloudstorage.com/userProfile/5/19","title":"123","content":"123","type":"FREEDOM","createDate":"2024/04/17 20:00:51","postImageUrls":[],"comments":[]},"error":null}

2024-04-17 11:17 UTC, rhkrwngud445 commented on feature/postlist/src/test/java/com/withpeace/withpeace/feature/postlist/PostListViewModelTest.kt
> +}
추후 공통함수로 빼도 되겠네요👍

2024-04-17 11:17 UTC, rhkrwngud445 commented on feature/postlist/build.gradle.kts
> +    }
어떤 경위로 추가되었는지, 알 수 있을까요?! 설명을 봐도 어떤 케이스로 추가되었는지 이해가 어렵네요🥲

2024-04-18 08:16 UTC, chws0508 commented on feature/postlist/build.gradle.kts
> +    }
로컬 테스트 시, 안드로이드 의존성이 있는 경우 (ex. Log) 모두 default 값으로 설정해주어 테스트가 실행될 수 있게 해줍니다. Paging테스트 진행시 Paging 내부에서 Log를 사용하는 것으로 보여졌고, 그래서 추가하게 되었습니다.

2024-04-18 08:17 UTC, chws0508 commented on core/ui/src/main/java/com/withpeace/withpeace/core/ui/DateUiModel.kt
> +    val duration: Duration
서버와 시간이 동일하지 않아서 생기는 문제인 것 같아요...!

2024-04-18 10:05 UTC, rhkrwngud445 approved these changes
고생하셨습니다!
시간이 상이한 부분은 백엔드와 같이 이야기해봅시다!

2024-04-19 03:53 UTC, merged