Feat/#91 댓글 기능을 구현한다
WithPeace/with-peace-android pull request #95
Opened 2024-04-19 13:35 UTC by chws0508

## 관련 이슈번호

<br/> close #91 

## 작업 사항

<br/>

## 기타 사항

<br/>

2024-04-20 10:18 UTC, rhkrwngud445 requested changes
고생하셨습니다! LazyListScope와 그 외 궁금한 점 위주로 남겼습니다!

또한 아래 신고하기 버튼은 추후 따로 구현되는 것일까요?!

<img width="299" alt="스크린샷 2024-04-20 오후 7 17 58" src="https://github.com/WithPeace/with-peace-android/assets/33768873/5a58d253-d894-46ce-98f4-b12244929ef9">

2024-04-20 10:18 UTC, rhkrwngud445 commented on feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/CommentSection.kt
> +fun LazyListScope.CommentSection(
현재 우리앱에 LazyListScope를 적용하면서 어떤 이점이 있나요?!

2024-04-20 10:18 UTC, rhkrwngud445 commented on feature/registerpost/src/main/java/com/withpeace/withpeace/feature/registerpost/RegisterPostViewModel.kt
> +                    delay(5000L)
delay를 주는 이유가 무엇일까요?!

2024-04-21 10:19 UTC, chws0508 commented on feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/PostDetailViewModel.kt
> +                when (it) {
서버에서 응답 형식을 바꿔서 저도 바꿔야 할 것 같습이다

2024-04-21 10:20 UTC, chws0508 commented on app/proguard-rules.pro
> +-dontwarn java.lang.instrument.UnmodifiableClassException
릴리즈 모드로 실행하는 과정에서 저걸 추가하라는 경고문이 떠서 추가하였습니더

2024-04-21 10:21 UTC, chws0508 commented on core/data/src/main/kotlin/com/withpeace/withpeace/core/data/util/image.kt
> +}
가로모드로 찍은 사진에 대해서 90도 회전하여 서버로 전송되는 현상에 대해 대응하는 코드입니다

2024-04-21 10:26 UTC, chws0508 commented on core/ui/src/main/java/com/withpeace/withpeace/core/ui/post/CommentUiModel.kt
> +)
preview할 때 쓰려고 디폴트값을 넣었는데 지우는게 나을 것 같네요.

2024-04-21 10:29 UTC, chws0508 commented on feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/CommentSection.kt
> +fun LazyListScope.CommentSection(
LazyList 안에 중복으로 LazyList를 넣을 수 없기 때문에 LazyListScope 확장함수를 이용하였습니다. 댓글과 본문이 한개의 LazyList 를 이용하여 스크롤이 되어야합니다

2024-04-21 10:29 UTC, chws0508 commented on feature/registerpost/src/main/java/com/withpeace/withpeace/feature/registerpost/RegisterPostViewModel.kt
> +                    delay(5000L)
실수 인 것 같습니다... 지우도록 하겠습니다

2024-04-21 10:30 UTC, chws0508 commented
신고하기는 신고하기 기능에 추가할 예정입니다

2024-04-22 13:31 UTC, rhkrwngud445 approved these changes
고생하셨습니다~~!

2024-04-29 12:45 UTC, merged